# .travis.yml
language: node_js
node_js:
  - "stable"
  - "6"
  - "5"
  - "4"
install:
  - npm install
script:
  - npm test
  - npm run cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"